trigger:
  batch: true
  branches:
    include:
      - master

jobs:
  - job: build_docker
    timeoutInMinutes: 180
    pool:
      vmImage: 'Ubuntu 16.04'

    variables:
      dockerId: pzalejko
      imageName: my-planner

    steps:
      - task: Maven@3
        displayName: 'Maven Build'
        inputs:
          jdkVersionOption: '1.11'
          goals: 'package'
          options: '-Pnative -Dnative-image.docker-build=true'
      - script: |
                       docker build -f docker/Dockerfile.native -t $(dockerId)/$(imageName) .
                       docker login -u $(dockerId) -p $(dockerPassword)
                       docker push $(dockerId)/$(imageName)
        displayName: 'build docker image'
