trigger:
  batch: true
  branches:
    include:
      - master

jobs:
  - job: build_docker
    timeoutInMinutes: 180
    pool:
      vmImage: 'Ubuntu 16.04'

    variables:
      dockerId: pzalejko
      imageName: my-planner

    steps:
      - script: |
                       docker build -t $(dockerId)/$(imageName) .
                       docker login -u $(dockerId) -p $(dockerPassword)
                       docker push $(dockerId)/$(imageName)
        displayName: 'build docker image'
