trigger:
  batch: true
  branches:
    include:
      - master

jobs:
  - job: build_docker
    timeoutInMinutes: 180
    pool:
      vmImage: 'Ubuntu 16.04'

    variables:
      dockerId: pzalejko
      imageName: my-runner

    steps:
      - task: Maven@3
        displayName: 'Maven Build'
        inputs:
          goals: 'package'
          options: '-Pnative -Dnative-image.docker-build=true'

      - script: |
                  docker build -f src/main/docker/Dockerfile.native -t $(dockerId)/$(imageName) .
        displayName: 'build docker image'

#      - task: Docker@0
#        displayName: 'Build an image'
#        inputs:
#          imageName: '$(dockerId)/$(imageName)'
#          containerregistrytype: 'Container Registry'
#          dockerRegistryConnection: myDockerHub
#          dockerFile: src/main/docker/Dockerfile.native

      - task: Docker@0
        displayName: 'Push an image'
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryConnection: myDockerHub
          action: 'Push an image'
          imageName: '$(dockerId)/$(imageName)'

#      - script: |
#                       docker build -f src/main/docker/Dockerfile.native -t $(dockerId)/$(imageName) .
#                       docker login -u $(dockerId) -p $(pswd)
#                       docker push $(dockerId)/$(imageName)
#        displayName: 'build docker image'
#        env:
#          pswd: $(dockerPassword)