version: '3'
services:
  myapp:
    build: .
    image: pzalejko/my-planner:latest
    container_name: "my-planner"
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.4
    container_name: "mongodb"
    ports:
      - 27017:27017
