version: '3'
services:
  myapp:
    image: pzalejko/my-planner:latest
    container_name: "my-planner"
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.2.1
    container_name: "mongodb"
    ports:
      - 27017:27017
  jaegertracing:
    image: jaegertracing/all-in-one:1.15.1
    container_name: "jaeger"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411