apiVersion: v1
kind: Service
metadata:
  name: my-planner
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "my-planner"
      port: 8080
  selector:
    app: my-planner